controller:
  name: "Virtual SDN Router"
  version: "1.0.0"
  listen_port: 6653
  api_port: 8080

intents:
  default_priority: 1
  policies:
    - name: "QoS Priority"
      priority: 100
      action: "high_priority"
    - name: "Load Balance"
      priority: 50
      action: "load_balance"
    - name: "SSL Inspection"
      priority: 80
      action: "inspect"
    - name: "Traffic Shaping"
      priority: 60
      action: "rate_limit"

logging:
  level: "INFO"
  file: "logs/controller.log"

openflow:
  version: "1.3"
  echo_interval: 15
  max_unreplied_echo: 3
